added WIP canvas FP defense based on Brave's farbling
polcak/jsrestrictor pull request #79
Opened 2021-01-09 21:11 UTC by xsvanc06

Adds pseudorandom noise based on Session and Domain hashes to canvas.toDataURL() function mentioned in #23

2021-01-11 13:42 UTC, polcak commented
Thank you,

* What is the license of the code?
* It would be nice to document the change in https://github.com/polcak/jsrestrictor/blob/master/docs/index.md
* See review comments.

2021-01-11 13:43 UTC, polcak requested changes

2021-01-11 13:43 UTC, polcak commented on common/domainHash.js
> +function gen_random32() {
AFAIK, this function is a part of the helpers.js, what is the reason of not using the one in helpers.js?

2021-01-11 13:43 UTC, polcak commented on common/domainHash.js
> +    parent.removeChild(script);
See injectScript() in inject.js

Anyway, what is the idea of this code? You polute global name space with variables `domainHash` and `sessionHash` which creates two problems:

* any page script can check if the variables are defined and based on this learn that the user is most likely using JSR,
* the page script can redefine the value of this variable.

2021-01-11 13:43 UTC, polcak commented on common/domainHash.js
> +chrome.storage.local.get(["sessionHash", "visitedDomains"], syncDomains);
Please document all storage data in https://github.com/polcak/jsrestrictor/blob/master/common/update.js.

Please use `browser` instead of `chrome`.

2021-01-11 13:43 UTC, polcak commented on common/sessionHash.js
> +function gen_random32() {
See above.

2021-01-11 13:43 UTC, polcak commented on common/wrappingS-H-C.js
> +					//console.log(sessionHash,domainHash);   ---for testing
Can this be omitted?

2021-01-11 13:43 UTC, polcak commented on common/wrappingS-H-C.js
> +        }],
It seems that there is a problem with indentation.

2021-01-11 13:43 UTC, polcak commented on common/wrappingS-H-C.js
> +				// TODO
What is the meaning of the comment?

2021-01-11 13:43 UTC, polcak commented on chrome/manifest.json
> +      "scripts": ["sessionHash.js", "helpers.js", "update.js", "url.js", WRAPPING, "code_builders.js", "levels.js", "background.js", "level_cache.js", "http_shield_chrome.js", "http_shield_common.js"
You'll probably need to move the script after helpers.js, see below.

Also looking at the other filenames, session_hash.js looks more consistent.

2021-01-11 13:43 UTC, polcak commented on common/domainHash.js
> +function gen_random64() {
This should be moved to helpers.js as well.

2021-01-11 13:53 UTC, polcak commented on chrome/manifest.json
>    "author": "Libor Polčák, Martin Bednář, Martin Timko, Pavel Pohner, Peter Horňák",
Do not forget to put your name here and to any file that you change, see also credits.md.

This is very important for the final submission of the thesis.

2021-02-12 12:15 UTC, polcak commented
I created a branch https://github.com/polcak/jsrestrictor/tree/brave (it is reabsed above 0.4.5 with atomic commits contained in this request), please can you update the commits as follows:

5e9dd688c4d685c6a5107a270cb0f219a9033ddf (contains canvas changes):
* mark code to be under MPLv2 licence with links to the Brave code if possible
* keep white canvas as an option, we should have a tick box than enables farbling

f76bb2864ea5b70432455880fa07d383975350a8 (audio wrappers):
* mark code to be under MPLv2 licence with links to the Brave code if possible

24ba0b4a20962164b76f8d379fce989802738529
* docs should contain both white background and farbling for Canvas

Once ready, you can force push to this request.

2021-02-26 01:04 UTC, xsvanc06 commented
Updated commits according to previous comment, if further changes are needed let me know. @polcak

2021-02-26 14:50 UTC, polcak commented
I am confused, the commits do not seem to be atomic and there is a lot of indentation errors. I tried to fix but failed.

Let us restart from https://github.com/polcak/jsrestrictor/tree/brave

The preferred way is to start with master and

* update canvas+levels etc. in one commit
* update audio in another commit
* update doc in another commit
* provide webgl in another commit

2021-02-26 15:44 UTC, polcak commented
Actually, I might have succeeded. Can you check https://github.com/polcak/jsrestrictor/tree/brave2?

If I missed something or you want to make another changes before merging, please provide separate commits with instructions if they should be squashed to an existing commit, rebased etc.

2021-02-26 15:49 UTC, polcak commented
Do you think that the OpenGL wrapper solves #50?

2021-02-26 19:23 UTC, xsvanc06 commented
Branch https://github.com/polcak/jsrestrictor/tree/brave2 seems to be okay.

Current state of WebGL wrapper solves #50 only partially. Some endpoints like https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/readPixels, https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/readBuffer and some other need to be covered.

2021-03-02 12:23 UTC, polcak requested changes
Also I noticed that there are WebGLRenderingContext.prototype.getFrameBufferAttachmentParameter, WebGLRenderingContext.prototype.getRenderBufferParameter in the webgl level.js group without defined wrappers.

2021-03-02 12:23 UTC, polcak commented on common/wrappingS-H-C.js
> +          fake.putImageData(imageData, 0, 0);
Indentation

2021-03-02 12:23 UTC, polcak commented on common/wrappingS-H-C.js
> +       * the content is copied to new canvas using CanvasRenderingContext2D and function toDataURL is called on it.
Indentation

2021-03-02 12:23 UTC, polcak commented on common/wrappingS-H-C.js
> +					var imageData = ctx.getImageData(0, 0, this.width, this.height);
this is just a formatting issue, ideally, it should be in a separate commit

2021-03-02 12:23 UTC, polcak commented on common/wrappingS-H-C.js
> +          var ctx = this.getContext("webgl2", {preserveDrawingBuffer: true}) ||
Indentation of the block

2021-03-02 12:23 UTC, polcak commented on common/levels.js
> +	"webgl_method": 1,
this seams to be unrelated

2021-03-02 12:23 UTC, polcak commented on common/wrappingS-WEBGL.js
> +	if(typeof vendor === 'undefined')
Please add curly braces around the one line block

2021-03-02 12:23 UTC, polcak commented on common/wrappingS-WEBGL.js
> +		var renderer = randomString(8);
Please add curly braces around the one line block

2021-03-02 12:23 UTC, polcak commented on common/wrappingS-WEBGL.js
> +	console.log(vendor);
This should be removed

2021-03-02 12:24 UTC, polcak commented on common/wrappingS-WEBGL.js
> +	console.log(vendor);
(console.log)

2021-03-05 14:56 UTC, polcak commented
Are https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/isPointInPath or https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/isPointInStroke modified by Brave?

2021-03-05 16:10 UTC, xsvanc06 commented
Yes, they both return false on maximum level of protection. I can add them to canvas wrapper.

2021-03-05 16:17 UTC, polcak commented
I am not sure that returning always false is the right approach but I think that you should add the wrappers and mark them with the \bug command so that we can improve the return value in the future. Or if you have a better idea, feel free to propose one.

I think that as a starting point we can consider learning the correct return value and modify it with a limited probability (say 5%). But there are caveats like preventing successive calls for the same pixel returning different values, returning inconsistent values for neighbourgh pixels etc.

2021-03-12 13:12 UTC, closed without merging